FROM hseeberger/scala-sbt:8u141-jdk_2.12.3_0.13.16 as compile-stage

ENV APP_HOME /analytics
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME

RUN sbt update
RUN sbt assembly


FROM flink:1.6.0

COPY --from=compile-stage /analytics/target/jars/* /analytics/target/jars/
COPY ./start-jobmanager.sh /analytics/start-jobmanager.sh
COPY ./wait-for-it.sh /analytics/wait-for-it.sh

ENTRYPOINT ["/bin/bash"]
CMD ["/analytics/start-jobmanager.sh"]
